apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: good-deployment
  labels:
    app: good-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: bad-deployment
  labels:
    app: bad-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: bad-deployment
  template:
    metadata:
      labels:
        app: bad-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: more-replicas-deployment
  labels:
    app: good-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: many-replicas-deployment
  labels:
    app: good-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80