run:
  modules-download-mode: readonly
output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  enable:
  - gofmt
  - goimports
  - unconvert
  - misspell
  - prealloc
