apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: policy-with-namespace
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  variables:
    - name: labels
      expression: "has(namespaceObject.metadata.labels) ? namespaceObject.metadata.labels : {}"
    - name: maxReplicas
      expression: "'max-replicas' in variables.labels ? int(variables.labels['max-replicas']) : 1"
  validations:
    - expression: object.spec.replicas <= variables.maxReplicas
      messageExpression: "'replicas must be less than ' + variables.maxReplicas"
