apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: policy-with-params
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  variables:
    - expression: "has(object.spec.replicas) ? object.spec.replicas : 1"
      name: replicas
  validations:
    - expression: variables.replicas < int(params.data.maxReplicas)
      messageExpression: "'replicas must be less than ' + params.data.maxReplicas"
