apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment
  namespace: default
  labels:
    app: good-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  namespace: default
  labels:
    app: bad-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: bad-deployment
  template:
    metadata:
      labels:
        app: bad-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: less-replicas-deployment
  namespace: default
  labels:
    app: good-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment-with-namespace
  namespace: foo
  labels:
    app: good-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment-with-namespace
  namespace: foo
  labels:
    app: bad-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: bad-deployment
  template:
    metadata:
      labels:
        app: bad-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: less-replicas-deployment-with-namespace
  namespace: foo
  labels:
    app: good-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80